import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import Navbar from "@/components/navigation/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const roboto = Roboto({
  weight: ["400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/* COLORS

background: bg-slate-950
secondary background: bg-slate-900

text: text-white
secondary text: text-gray-300

main: text-cyan-300
secondary color: text-red-400

*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} bg-background text-white`}>
        <Navbar />

        <div className="min-h-screen mt-14 sm:mt-16 md:mt-20 px-4 sm:px-6 lg:px-20">
          {children}
        </div>

        <Footer />
      </body>
    </html>
  );
}
